### ISSUE TITLE
Error uploading file: 401

### ISSUE THREAD

**Issue by DarknightCanada** [Octoberfest7/TeamsPhisher#1]
First of all thank you for the tool!

I am testing your tool however it fails to upload file on SharePoint! I made sure my user has the full control rights to upload file on SharePoint however keeps failing! Any insight of how can I fix it?

`Operational mode: Sending phishing messages to targets!

Time left to abort: 00

Authenticating, verifying files, and uploading attachment

Reading target email list..................................................[+] SUCCESS!
Fetching Bearer token for Teams............................................[+] SUCCESS!
Fetching Skype token.......................................................[+] SUCCESS!
Fetching sender info.......................................................[+] SUCCESS!
Fetching Bearer token for SharePoint.......................................[+] SUCCESS!
Uploading file: .\README.MD................................................[-] Error uploading file: 401`

**Comment by Octoberfest7** [comment]
401 means "Unauthorized"... Which is strange given you successfully retrieved the SharePoint token.

at line 326 in the program there is this: 
```
    # Seem to have seen both of these codes for file uploads...
    if content.status_code != 201 and content.status_code != 200:
        p_err("Error uploading file: %d" % (content.status_code), True)
```
make it look like this and re-run it in order to see the headers and body of the error
```
    # Seem to have seen both of these codes for file uploads...
    if content.status_code != 201 and content.status_code != 200:
        p_err("Error uploading file: %d" % (content.status_code), True)
        print(content.headers)
        print(content.text)
```

**Comment by DarknightCanada** [comment]
Same! Do not want to take much of your time but plz if you think of any other way to troubleshoot it let me know please. FYI! I can manually upload files on sharepoint  
`Authenticating, verifying files, and uploading attachment

Reading target email list..................................................[+] SUCCESS!
Fetching Bearer token for Teams............................................[+] SUCCESS!
Fetching Skype token.......................................................[+] SUCCESS!
Fetching sender info.......................................................[+] SUCCESS!
Fetching Bearer token for SharePoint.......................................[+] SUCCESS!
Uploading file: .\README.MD................................................[-] Error uploading file: 401`

**Comment by Octoberfest7** [comment]
My bad, make it look like this: 

```
    # Seem to have seen both of these codes for file uploads...
    if content.status_code != 201 and content.status_code != 200:
        print(content.headers)
        print(content.text)
        p_err("Error uploading file: %d" % (content.status_code), True)
```

The way I had you do it before made the program exit before it printed the headres and text

**Comment by DarknightCanada** [comment]
Same thing dude! I am going to play with the python script to see if I can get it to work! thanks for taking the time to respond 

`Configuration:

[-] Sending file link that is accessible by anyone with the link
[-] No delay between messages
[+] Using greeting: Hi, --personalize greeting: Hi <Name>,
[-] Not logging TeamsPhisher output

Operational mode: Sending phishing messages to targets!

Time left to abort: 00

Authenticating, verifying files, and uploading attachment

Reading target email list..................................................[+] SUCCESS!
Fetching Bearer token for Teams............................................[+] SUCCESS!
Fetching Skype token.......................................................[+] SUCCESS!
Fetching sender info.......................................................[+] SUCCESS!
Fetching Bearer token for SharePoint.......................................[+] SUCCESS!
Uploading file: .\README.MD................................................[-] Error uploading file: 401`

**Comment by Octoberfest7** [comment]
You still got no output? As a sanity check, add a prefix to the print statements so you can be sure they are actually executing

    # Seem to have seen both of these codes for file uploads...
    if content.status_code != 201 and content.status_code != 200:
        print("failed headers: " + str(content.headers))
        print("failed body: " + str(content.text))
        p_err("Error uploading file: %d" % (content.status_code), True)

**Comment by DarknightCanada** [comment]
oK now I ma getting output! `Uploading file: .\target.txt...............................................failed headers: {'Cache-Control': 'private', 'Content-Type': 'application/json', 'Server': 'Microsoft-IIS/10.0', 'X-NetworkStatistics': '0,525568,0,0,219,0,23728', 'Access-Control-Allow-Origin': '*', 'Access-Control-Max-Age': '2592000', 'Access-Control-Expose-Headers': 'Accept-Ranges, Content-Encoding, Content-Length, Content-Type, Content-Version, CTag, ETag, Location, spclientservicerequestduration, SPRequestDuration, SPRequestGuid, Timing-Allow-Origin, Transfer-Encoding, WWW-Authenticate, X-Fluid-Epoch, X-Fluid-Retries, X-Fluid-SLTelemetry, X-Fluid-Telemetry, X-MoveState, x-ms-diagnostics', 'X-DataBoundary': 'EU', 'X-1DSCollectorUrl': 'https://eu-mobile.events.data.microsoft.com/OneCollector/1.0/', 'X-AriaCollectorURL': 'https://eu-mobile.events.data.microsoft.com/Collector/3.0', 'SPRequestGuid': '73f2c2a0-b071-6000-db58-5691517a23a0', 'request-id': '73f2c2a0-b071-6000-db58-5691517a23a0', 'MS-CV': 'oMLyc3GwAGDbWFaRUXojoA.0', 'Report-To': '{"group":"network-errors","max_age":7200,"endpoints":[{"url":"https://spo.nel.measure.office.net/api/report?tenantId=00000000-0000-0000-0000-000000000000&destinationEndpoint=190162&frontEnd=FarmDirect"}]}', 'NEL': '{"report_to":"network-errors","max_age":7200,"success_fraction":0.001,"failure_fraction":1.0}', 'Strict-Transport-Security': 'max-age=31536000', 'X-FRAME-OPTIONS': 'SAMEORIGIN', 'Content-Security-Policy': "frame-ancestors 'self' teams.microsoft.com *.teams.microsoft.com *.skype.com *.teams.microsoft.us local.teams.office.com teams.microsoftonline.cn *.powerapps.com *.yammer.com *.officeapps.live.com *.office.com *.stream.azure-test.net *.microsoftstream.com *.dynamics.com *.microsoft.com onedrive.live.com *.onedrive.live.com securebroker.sharepointonline.com;", 'SPRequestDuration': '32', 'SPIisLatency': '1', 'x-ms-suspended-features': 'features=""', 'X-Powered-By': 'ASP.NET', 'MicrosoftSharePointTeamServices': '16.0.0.23814', 'X-Content-Type-Options': 'nosniff', 'X-MS-InvokeApp': '1; RequireReadOnly', 'P3P': 'CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"', 'WWW-Authenticate': 'Bearer realm="aa50bdd8-e6c1-41df-a463-54ec17c72d09",client_id="00000003-0000-0ff1-ce00-000000000000",trusted_issuers="00000001-0000-0000-c000-000000000000@*,D3776938-3DBA-481F-A652-4BEDFCAB7CD8@*,https://sts.windows.net/*/,https://login.microsoftonline.com/*/v2.0,00000003-0000-0ff1-ce00-000000000000@90140122-8516-11e1-8eff-49304924019b",authorization_uri="https://login.microsoftonline.com/common/oauth2/authorize"', 'Date': 'Mon, 03 Jul 2023 18:18:36 GMT', 'Content-Length': '145'}
failed body: {"error":{"code":"unauthenticated","innerError":{"code":"invalidAudienceUri"},"message":"Invalid audience Uri 'https://darknight-my.sharepoint.com/'."}}`

**Comment by DarknightCanada** [comment]
interesting! it is using this url  "'https://darknight-my.sharepoint.com/"

**Comment by Octoberfest7** [comment]
Hey send me a DM on twitter @Octoberfest73 or on discord at octoberfest (Octoberfest#0860)

**Comment by Octoberfest7** [comment]
The issue in this case was that when the user created their AAD tenant they gave the tenant a different 'Organization Name' than their 'Initial Domain Name' like in the below screenshot:

![image](https://github.com/Octoberfest7/TeamsPhisher/assets/91164728/40c44454-3440-45b6-8b5a-a0e783bd45fc)

I truthfully didn't know/remember that there were two separate fields there or that someone might make them different. TeamsPhisher uses the 'tenantName' property to resolve the Sharepoint address, so in this case it was looking for Sharepoint at 'myorgname-my.sharepoint.com...' when it really lives at 'myorgnameiscool-my.sharepoint.com'

I may look at fixing this in the future, as I could just split out the domain name from the UPN e.g. 'tomjones@mycoolorg.onmicrosoft.com' would return 'mycoolorg' as the 'tenantName' field for subsequent use.
