### ISSUE TITLE
Different urls for a non-english tenant 

### ISSUE THREAD

**Issue by mbst83r** [Octoberfest7/TeamsPhisher#13]
Hello, 

nice work. But I think you need a different url for a non-english tenant.

In a german tenant, for example "Microsoft Teams Chatfiles" does not exist, but "Microsoft Teams Chatdateien" exists.

Maybe you can add an option to specify this, if you find some time.

Also the user domain part from a specified sharepoint server can be different too : 

senderDrive = "%s_%s_onmicrosoft_com" 

Best regards
mbst83r

**Comment by Octoberfest7** [comment]
Hey thanks for the report. Unfortunately I cannot support all of the different possibilities out there for different languages around the world. If someone else wants to work on this they are welcome to. Filing this as a "will not fix".
