### ISSUE TITLE
Error in Module Payload

### ISSUE THREAD

**Issue by SarThom** [Octoberfest7/TeamsPhisher#14]
Hi,

tried it today and got Errors:
[error.txt](https://github.com/Octoberfest7/TeamsPhisher/files/11999507/error.txt)

am I doing anything wrong?

**Comment by Octoberfest7** [comment]
Idk what is producing 156k worth of logs, but that isn't readable or useful for me. Take a screenshot or copy/paste just the normal stack trace you get when it fails.
