### ISSUE TITLE
Speed up user retrieval

### ISSUE THREAD

**Issue by gg-g** [Octoberfest7/TeamsPhisher#15]
https://github.com/Octoberfest7/TeamsPhisher/blob/c5fb827d79eb4ad43df8b77a48a683523164f6a9/teamsphisher.py#L213

add &top=999 parameter to increase the page size for user list retrieval

> url += f"?skipToken={skipToken}"

to

> url += f"?skipToken={skipToken}&top=999"

**Comment by Octoberfest7** [comment]
Add in [4e34fce](https://github.com/Octoberfest7/TeamsPhisher/commit/4e34fce51c0f428ef642365e9eceec5c3cd0d82d)

Thanks
