### ISSUE TITLE
Input parameter 'scope' is not valid

### ISSUE THREAD

**Issue by blockanz** [Octoberfest7/TeamsPhisher#2]
When running the tool, I can successfully authenticate my device, however when the tool gathers the SharePoint bearer token it seems to be adding in a space between the first part of the URL. i.e. my domain is fredbloggs.com, and when getting the token the error shows https://fred bloggs-my.sharepoint.com

Not sure what is causing this though. Any ideas?

**Comment by Octoberfest7** [comment]
Kind of sounds like the same issue seen here: https://github.com/Octoberfest7/TeamsPhisher/issues/1

The sharepoint address is assembled by taking the "tenantName" field that is queried for your user; I'm guessing that you named your tenant "fred bloggs", by the domain name is "fredblogs.com". Given you are the second person with this issue I'll make the change and push it up shortly

**Comment by Octoberfest7** [comment]
pull the latest commit and then give it another shot

**Comment by blockanz** [comment]
Yes, that was the issue. Changed the tenant name and voila. I'll pull the latest commit and change the name back and see what happens.

Many thanks for the prompt response.
