### ISSUE TITLE
.[-] Error fetching sharing link: 500 {"error":{"code":"-1, System.Text.DecoderFallbackException","message":{"lang":"es-ES","value":"Unable to translate bytes [ED] at index 460 from specified code page to Unicode."}}}

### ISSUE THREAD

**Issue by kinomakino** [Octoberfest7/TeamsPhisher#25]
First of all, thanks for the tool
I get this error when trying to send the message:
.[-] Error fetching sharing link: 500
{"error":{"code":"-1, System.Text.DecoderFallbackException","message":{"lang":"es-ES","value":"Unable to translate bytes [ED] at index 460 from specified code page to Unicode."}}}

**Comment by Octoberfest7** [comment]
I would guess you are using a different language than English and there are encoding issues that result from non-English characters being used

**Comment by kinomakino** [comment]
True, sorry.
