### ISSUE TITLE
Log file has a colon : (illegal character) in it for the time, creates an empty file with just the "hour" for the name

### ISSUE THREAD

**Issue by GThomas-ent** [Octoberfest7/TeamsPhisher#5]
On Windows 11.
Used the --log switch (I can't chose a name, I believe by design).
It attempts to create a file:

[+] Logging TeamsPhisher output at: C:\Users\MYUSERNAME/13:11_06Jul23_teamsphisher.log

All that is created is an empty file called "13" - in the correct location.  This is just before the illegal character ":"

**Comment by Octoberfest7** [comment]
Yeah I developed this on Linux and didn't think about potential issues with file names on Windows. Just pushed a commit 3d5770f to address this, should fix it.

**Comment by GThomas-ent** [comment]
Thanks, so fast! Confirmed working.
