### ISSUE TITLE
possible sharepoint leak

### ISSUE THREAD

**Issue by Danielg75** [Octoberfest7/TeamsPhisher#7]
https://github.com/Octoberfest7/TeamsPhisher/blob/3d5770feb654e5034b730b2ff8f8c313addce2fb/teamsphisher.py#L424

Why does this line contain references to https://teamphisher-my.sharepoint.com/personal/phisher_teamphisher_onmicrosoft_com? This message is sent to victims and contains our sharepoint but also sends your sharepoint URL.

**Comment by LaRancion** [comment]
seems strange as it uses the info of our sharepoint (URL and Shareid) in the link with the teamphisher sharepoint `inviteInfo.get('d').get('ShareLink').get('sharingLinkInfo').get('Url'),inviteInfo.get('d').get('ShareLink').get('sharingLinkInfo').get('ShareId')`

I ight be wrong tough

**Comment by Octoberfest7** [comment]
This was an oversight on my part and has been fixed. Thanks for your report. If you wouldn't mind editing/scrubbing your issue I would appreciate it.

**Comment by Danielg75** [comment]
I can edit my issue, however history is preserved in GIT, so it can't entirely be erased as your edit will be traceable.

**Comment by Octoberfest7** [comment]
Yeah understood. I appreciate you looking out.
